### PR TITLE
Xcode 10 updates

### PR DESCRIPTION
**Pull request by SergeyKuryanov**
Update project to support Xcode 10 and latest Swift 4.2.
As part of this PR https://github.com/adamyanalunas/Font/issues/9 was fixed as well

Project should build without warnings and tests should pass.

### CODE REVIEW

**Comment by SergeyKuryanov** [comment]
@adamyanalunas not sure why it is failed and I can't restart build. May you please help with restarting?

**Comment by adamyanalunas** [comment]
@SergeyKuryanov I restarted the build but it failed again. I think this may have something to do with the Ruby version defined in `.ruby-version`. With the xcode10.1 image Travis ships with [Ruby 2.4.5](https://blog.travis-ci.com/2018-11-01-xcode-10-1-is-now-available), which is higher than the 2.2.4 defined in the `.ruby-version`. Maybe update the local version in this PR to 2.4.5 and see if that makes Travis happy?

**Comment by SergeyKuryanov** [comment]
@adamyanalunas updated, thanks for helping in debug.

**Comment by adamyanalunas** [comment]
Nice PR! Thanks for taking care of #9. ⛵️

**Pull request merged**
